export interface liq_comision_supervisor {
    id: number,
    mes_comision: number,
    periodo: string,
    codigo_tipo_esquema: number,
    nombre_esquema : string,
    cedula_supervisor: string,
    nombre_supervisor : string,
    numero_meta_ftth: number,
    numero_cumplimiento_asesor_ftth: number,
    porcentaje_cumplimiento_asesor_ftth: string,
    homologa_porcentaje_ftth: number,
    peso_cumpliento_ftth: string,
    homologa_peso_ftth: number
    numero_meta_movil: number,
    numero_cumpliento_asesor_movil: number,
    porcentaje_cumplimiento_asesor_movil: string,
    homologa_porcentaje_movil: number,
    peso_cumplimiento_movil: string
    homolog_peso_movil: number,
    numero_cumplimiento_asesor_lb: number,
    porcentaje_cumplimiento_asesor_lb: string,
    homologa_porcentaje_lb: number,
    numero_meta_lb: number,
    peso_cumplimiento_lb: string,
    homologa_peso_cumplieminto_lb: number,
    numero_cumplimiento_asesor_tv: number,
    porcentaje_cumplimiento_asesor_tv: string,
    homologa_porcentaje_tv: number,
    numero_meta_tv: number,
    peso_cumplimiento_tv: string,
    homologa_peso_tv: number,
    comision: number,
    factor_acelearion_desaceleracion: string,
    homologa_factor_aceleracion_desaceleracion: number,
    total_comision: number,
    total_porcentaje_cumplimiento: string,
    total_homologa_cumplimiento: number,
    aceleracion_desaceleracion: string,
    
}