export interface tmp_data_empleado{
    id ? : number,
    cedula : string,
    sedeprinicipal : string,
    nombrecompleto : string,
    codigocargo : string,
    cargo : string,
    contrato : string,
    centrodecostos : string,
    nombrececo : string,
    area : string,
    subarea : string,
    cupo : string,
    empresacontratante : string,
    tipodecontratolaboral : string,
    ciudadprestacionservicios : string,
    rangosalarial : string,
    salario : string,
    fechadeingreso : Date,
    fechaderetiro :Date,
    causalderetiro : string,
    observaciones : string,
    plandebeneficios : string,
    fechainicioplandebeneficios : Date,
    sintraoptecom : string,
    fechaingresoSOp : Date,
    fecharetiroSOp : Date,
    sintrainducom : string,
    fechaingresoSintra :Date,
    fecharetiroSintra :Date,
    sindicatoSNTC :string,
    fechaingresoSNTC : Date,
    fecharetiroSNTC :Date,
    nivelriesgoarl : string,
    fechanacimiento : Date,
    lugarnacimiento : string,
    departamentonacimiento : string,
    lugarexpedicioncedula :string,
    departamentoexpidicioncedula : string,
    sexo : string,
    tipodesangre : string,
    direccionresidencia : string,
    ciudadresidencia : string,
    telefono : string,
    correoelectronico : string,
    correocorporativo : string,
    nocuentabancaria : string,
    eps : string,
    fondopension : string,
    fondocesantias : string,
    estadocivil : string,
    ndehijos : string,
    auxiliorodamiento : string,
    auxiliomovilidad : string,
    auxilioportatil : string,
    auxiliocelular : string,
    auxilioteletrabajo : string,
    modalidateletrabajo : string,
    otrosi : string,
    fechainicioOTROSI : Date,
    tipodeempleado : string,
    concatenado : string,
    validadorsalario : string,
    salarioantes : string,
    salariototal : string,
    entidadbancaria : string
}